mapunit1 <- function() {
  c('GL' = 'Glacier',
    'PN' = 'Snow Cover Water',
    'LA' = 'Lake',
    'RI' = 'River/Stream',
    'OC' = 'Ocean Exposed Land',
    'MZ' = 'Rubbly Mine Spoils',
    'LB' = 'Lava Bed',
    'RS' = 'River Sediments',
    'ES' = 'Exposed Soil',
    'LS' = 'Pond or Lake Sediments',
    'LL' = 'Landing',
    'RZ' = 'Road Surface',
    'CB' = 'Cutbank',
    'MN' = 'Moraine',
    'GP' = 'Gravel Pit',
    'TZ' = 'Tailings',
    'RN' = 'Railway Surface',
    'UR' = 'Urban',
    'AP' = 'Airport',
    'MI' = 'Open Pit Mine',
    'ST' = 'SkidTrail',
    'RP' = 'Road Permanent')
}
